version: '3.4'
networks:
  constr-sw-2023-1:
volumes:
  constr-sw-2023-1-keycloak-data:
    external: true
services:
  # Keycloak
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
    volumes:
      - constr-sw-2023-1-keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - constr-sw-2023-1
