version: '3.4'
networks:
  grupo-06:
volumes:
  grupo-06-keycloak-data:
    external: true
services:
  # Keycloak
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=a12345678
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
    volumes:
      - grupo-06-keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - grupo-06

  # Node.js
  node:
    container_name: node
    image: node:latest
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: sh -c "npm install && npm run dev-docker"
    networks:
      - grupo-06
